doc/index.rst, doc/overview.rst, examples/ex_02_probe_2d_probe_3d.py, examples/ex_07_more_plotting_examples.py, probeinterface/plotting.py, probeinterface/probe.py, tests/test_plotting.py, tests/test_probe.py
=> Make rotation and refactor plotting.

doc/format_spec.rst, doc/generate_format_example.py, doc/overview.rst, examples/ex_01_generate_probe_from_sratch.py, examples/ex_02_probe_2d_probe_3d.py, examples/ex_03_generate_probe_group.py, examples/ex_04_multi_shank_probe.py, examples/ex_05_device_channel_indices.py, examples/ex_06_import_export_to_file.py, examples/ex_07_probe_generator.py, examples/ex_08_more_plotting_examples.py, examples/ex_09_more_complicated_probe.py, examples/ex_10_get_probe_from_library.py, examples/ex_11_automatic_wiring.py, probeinterface/__init__.py, probeinterface/generator.py, probeinterface/io.py, probeinterface/library.py, probeinterface/plotting.py, probeinterface/probe.py, probeinterface/probegroup.py, probeinterface/shank.py, probeinterface/utils.py, probeinterface/wiring.py
API changes:
`combinate_probes` --> `combine_probes`
=> Correct and improve docs

probeinterface/io.py
Playing with the software. Maybe I'm doing something wrong, since when plotting the probe, the scale for xaxis and yaxis are clearly not optimal. However, the layout seems correct...
=> Adding maxwell probe layout

probeinterface/probe.py, tests/test_probe.py
This PR fixes the validation of the shank_id array and adds a corresponding test
=> Fix shank id checks and add test

probeinterface/generator.py, probeinterface/io.py, probeinterface/probe.py, probeinterface/probegroup.py, tests/test_probe.py
This PR is a collection of various small typo and documentation fixes. This is only a collection is by far not complete, as I didn't scan the complete probeinterface code systematically, but it's at least a start.
=> Various small fixes for typos and clarifications

probeinterface/probe.py, tests/test_probe.py
adding functionality to import probe information from a pandas dataframe
=> add from_dataframe method

probeinterface/__init__.py, probeinterface/io.py, probeinterface/probe.py, probeinterface/probegroup.py, probeinterface/utils.py, tests/test_io.py, tests/test_probegroup.py
This PR adds the capability to export and import data from probeinterface to a probe description format as it is currently under discussion for a [preliminary BEP proposal](https://docs.google.com/document/d/1oG-C8T-dWPqfVzL2W8HO3elWK8NIh2cOCPssRGv23n0/edit#heading=h.7kenzwjry86m)
The proposed format for integration into BIDS is still under development, so changes are expected in the future. This PR is a prove of concept, that a translation between probeinterface and the proposed format is possible.
The code itself can probably simplified further in the future, but is accompanied already by some test.
=> Add support for suggested BEP probe files

probeinterface/io.py
- works with MEArec file on GIN by adding extra checks
=> More checks for MEArec reader

README.md, examples/ex_03_generate_probe_group.py, examples/ex_05_device_channel_indices.py, examples/ex_06_import_export_to_file.py, examples/ex_07_probe_generator.py, probeinterface/__init__.py, probeinterface/generator.py, probeinterface/io.py, probeinterface/library.py, probeinterface/plotting.py, probeinterface/probe.py, probeinterface/probegroup.py, probeinterface/shank.py, probeinterface/utils.py, probeinterface/wiring.py, tests/test_io.py, tests/test_plotting.py
* Fix some typos
* Ensure consistent formatting for docstrings
=> Clean up comments

probeinterface/plotting.py, tests/test_plotting.py
@alejoe91 : to make you happy.
=> Implement show_channel_on_click.

probeinterface/io.py, probeinterface/probe.py, probeinterface/probegroup.py
- and annotate maxwell probe with `electrode` id
=> Add array annotation to numpy representation

probeinterface/__init__.py, probeinterface/io.py
=> Add 3brain reader

probeinterface/plotting.py, tests/test_plotting.py
@alejoe91 : can you look at this ?
=> Add "text_on_contact" in plot_probe()

doc/release_notes.rst, doc/releases/0.2.10.rst, probeinterface/version.py
=> prepare release 0.2.10

probeinterface/io.py
@MarineChap 
@jsiegle told me that the BASESTATION is not a reliable field to infer probe names (since there are different options to populate it, including the use of CUSTOM_PROBE_NAMES).
The best way to assign probe names is to get them from the STREAMs and then assign them to each NP_PROBE field sequentially. This PR  implements that.
=> Do not rely on BASESTATION field to parse OpenEphys probe

doc/release_notes.rst, doc/releases/0.2.12.rst, pyproject.toml
Try to deploy the paquage with pyproject.toml
=> release 0.2.12

resources/generate_cambridgeneurotech_libray.py
Regenerate the entire cambridge neurotech library with file from Jessie Goins received July 2022 July
=> Regenerate the entire cambridge neurotech

probeinterface/io.py
With the latest version of spikeinterface the ability for probe interface to read the metadata from phase3A neuropixel arrays (documented by Bill Karsh [here](https://billkarsh.github.io/SpikeGLX/Support/Metadata_3A.html)) was lost. I have added a section to the code in order to allow these files to be read once again.
=> including ability to read phase3A neuropixel arrays

doc/release_notes.rst, doc/releases/0.2.15.rst
- Bug fix for Open Ephys version parsing
=> Prepare 0.2.15 release

doc/format_spec.rst, doc/index.rst, doc/library.rst, doc/overview.rst
I was just fixing some typos in the doc folder. Only one question for big review:
in index.rst line 11 it only had the letter 's' I assumed that was shank, but if it was suppose to be a different word just let me know.
=> Improve Documentation - I

doc/overview.rst, examples/ex_02_probe_2d_probe_3d.py, examples/ex_04_multi_shank_probe.py, examples/ex_05_device_channel_indices.py, examples/ex_06_import_export_to_file.py, examples/ex_08_more_plotting_examples.py, examples/ex_09_more_complicated_probe.py, examples/ex_11_automatic_wiring.py, examples/ex_12_plot_values.py
@samuelgarcia I wasn't sure if for this repo you automatically generated files for the readthedocs from the .py or if you needed me to convert them myself first. Just let me know if you want me to convert them to .rst first. 
I just fixed a few typos in the examples, but I love the sense of humor so I made sure not to touch that.
=> Improve Documentation - II

.github/workflows/full_tests.yml, README.md, pyproject.toml
This PR addds the actions for the built status, licence, etc.
Moreover, it adds code coverage to actions. 
EDIT: secret for code cov is available.
=> Add badges and code coverage to actions

.github/workflows/full_tests.yml
I need this to get the code coverage right.
=> Cron job and manual trigger for CI tests

probeinterface/io.py
Following on #166 and #167 and build on a suggestion by @alejoe91 this PR consolidates all the information of each of the probes in one place and fetches it a run time to run the probe. This is in opposition to the previous approach where the nested structure was inside the function.
=> Consolidate neuropixel information in one place

.pre-commit-config.yaml
=> Add pre-commit configuration file

src/probeinterface/generator.py
=> Fix y_shift_per_column docs and add assertion

src/probeinterface/io.py
As in title, see https://github.com/NeuralEnsemble/python-neo/pull/1464#pullrequestreview-2028768919
=> Add NP1016 (same as 1015)

src/probeinterface/probe.py
I  added the dtype of the structure array the `to_numpy`` function produces.
=> Add dtype information to to_numpy function docstring

doc/release_notes.rst, doc/releases/0.2.23.rst
Just one feature addition for newly distributed NP1 probes #286
=> Release 0.2.23

src/probeinterface/io.py
=> Fix open-ephys load with serial number as custom probe name

resources/generate_cambridgeneurotech_libray.py
@alejoe91 : I need this merge only to keep track of the generation of CN
=> Regenerate ASSY-1-P1 and ASSY-1-P2

doc/releases/0.2.27.rst, pyproject.toml
=> Fix hatchling packaging

doc/release_notes.rst, doc/releases/0.2.29.rst, doc/releases/0.3.0.rst, pyproject.toml
=> Prepare 0.3.0 release
