- probeinterface/probe.py
- tests/test_probe.py
Protect some attributes with setter:
* contact_positions
* contact_plane_axes
* contact_shapes
* contact_shape_params
This should avoid direct setting and some errors.
@JuliaSprenger @alejoe91 : could you give some feedback ?
> Protect some attributes with setters.

- probeinterface/__init__.py
- probeinterface/io.py
- tests/OE_Neuropix-PXI/settings.xml
- tests/test_io.py
From version 0.3.3, the `Neuropix-PXI` open ephys plugin saves electrode locations (see https://github.com/open-ephys-plugins/neuropixels-pxi/releases)
This PR adds a `read_openephys()` function to instantiate a `Probe` object from it
> Add read_openephys function for Neuropux-PXI plugin

- examples/ex_01_generate_probe_from_sratch.py
- examples/ex_02_probe_2d_probe_3d.py
Renaming the keyword parameter `plane` to `axes` in d2cd928 was, strictly speaking, a breaking API change.
This PR adjusts the examples to match the new API.
Fixes:
```
TypeError: to_3d() got an unexpected keyword argument 'plane'
```
when running the examples.
> Adjust examples to use to_3d(axes=…)

- probeinterface/io.py
It the Neuropixels probe type was unknown (e.g. for NP-Ultra), the `contact_ids` were set to `[]`, which triggered errors whrn running `to_numpy()`.
This PR simply avoids setting contact ids when they ar enot known.
> Better handling of contact ids for unknown NP type in OpenEphys

- probeinterface/io.py
For the tests data in spikeinterface the description is a bytes object. This is a small fix so it actually decodes to a string.
> Mearec description to string

- .github/workflows/full_tests.yml
Couple of things in this PR:
1) Update the actions versions.
2) Use a newer version of Python
3) Eliminate `ready_for_review` condition (I don't see the point of this if it was tested again when it was synchronized). Maybe @samuelgarcia would like some of this small power saving ; )
4) Re-name the yml file to `full_tests.yml`
Let's leave testing other operating systems for later.
> Update test workflow to use latest version of actions

- .github/workflows/full_tests.yml
- tests/test_io/test_io.py
Currently, the tests are generating temporary files locally as a side effect of running them.
This PR adds uses pytext fixtures to route them to a temporary directory.
> Handle temporary files in the test suite

- probeinterface/io.py
- probeinterface/utils.py
- tests/test_utils.py
Commonly we use the pattern for safe import of:
```
try:
import package
except:
raise
```
This PR centralizes this logic using importlib to have a place where the logic of failure is handled and adds a test.
> Add safe import

- probeinterface/plotting.py
Fixed `DeprecrationWarning: invalid escape sequence \m`
> Fix little bug

- src/probeinterface/probe.py
The current docstring seems to be a bit unclear for `plane_axes`
See https://github.com/SpikeInterface/spikeinterface/issues/1727
> Small docs improvement for set_contacts plane_Axes

- src/probeinterface/probe.py
- tests/test_io/test_io.py
As in spikeinterface
https://github.com/SpikeInterface/spikeinterface/pull/2002
> `np.in1d` to `np.isin` as the former will be deprecated 

- doc/library.rst
There were also a few references to gin left that I removed, but let me know if you'd like the wording to be tweaked more.
> Add more details to how to contribute

- src/probeinterface/io.py
- src/probeinterface/library.py
- src/probeinterface/probe.py
- tests/test_io/test_openephys.py
- tests/test_io/test_spikeglx.py
This PR adds and unifies the `serial_number`/`model_name`/`manufacturer` annotations.
The `Probe()` constructor can now take these optional argument to automatically populate the annotations. This does not change the probeinteface format specification.
I also unified the serial number retrieval from Open Ephys and SpikeGLX, plus additional metadata.
Fixes #203
> Extend probe constructor

- doc/generate_format_example.py
- examples/ex_03_generate_probe_group.py
- examples/ex_05_device_channel_indices.py
- examples/ex_06_import_export_to_file.py
- examples/ex_07_probe_generator.py
- examples/ex_10_get_probe_from_library.py
- examples/ex_11_automatic_wiring.py
- resources/generate_cambridgeneurotech_libray.py
- src/probeinterface/generator.py
- src/probeinterface/io.py
- src/probeinterface/plotting.py
- src/probeinterface/probe.py
- src/probeinterface/probegroup.py
- tests/test_generator.py
- tests/test_io/test_io.py
- tests/test_io/test_openephys.py
- tests/test_io/test_spikeglx.py
- tests/test_plotting.py
- tests/test_wiring.py
* Remove channel_index concept.
* Make contact_ids in generator.
* Remove assertion for unique contact_ids in ProbeGroup.
* other fixes related
> Remove channel index concept

- README.md
- doc/release_notes.rst
- doc/releases/0.2.18.rst
- pyproject.toml
- added release notes
- added `sphinx_rtd_theme` to `[docs]` installation
- updated README to be in "sync" with SpikeInterface
> Prepare 0.2.18 release

- src/probeinterface/io.py
The `RECORDING_STATE` should be skipped if `ALL` or `NONE` (currently it's just `ALL`)
> Fix Open Ephys recording state options

- .gitignore
- src/probeinterface/generator.py
- src/probeinterface/io.py
- src/probeinterface/library.py
- src/probeinterface/plotting.py
- src/probeinterface/probe.py
- src/probeinterface/probegroup.py
- src/probeinterface/shank.py
- src/probeinterface/utils.py
- src/probeinterface/wiring.py
- tests/test_io/test_io.py
- tests/test_shank.py
So I switched most of the docstrings over to the SI format (I'm sure I'm missed some though) and I tried to add assert messaging to help users.
> Make docstrings-style compliant and add assert messaging

- src/probeinterface/io.py
* Missing: test file for brw v4.x file format
See also NeuralEnsemble/python-neo/issues/1324 and corresponding NeuralEnsemble/python-neo/pull/1326
> Add support for Biocam brw v4.x files

- .pre-commit-config.yaml
- pyproject.toml
- tests/test_generator.py
- tests/test_io/test_io.py
- tests/test_io/test_openephys.py
- tests/test_io/test_spikeglx.py
- tests/test_library.py
- tests/test_plotting.py
- tests/test_probe.py
- tests/test_probegroup.py
- tests/test_shank.py
- tests/test_utils.py
- tests/test_wiring.py
Will make the diff of #248 easier to read.
> Black format tests

- src/probeinterface/probe.py
- tests/test_probe.py
Something that came up when working on the Templates object. Added the method and a test.
> Add equality dunder method and test to `Probe` object

- src/probeinterface/probe.py
- tests/test_probe.py
Right now we have the following behavior:
```python
from probeinterface import Probe
probe = Probe(ndim=2, si_units='um', name="probe_name")
print(probe.annotations)
probe2 = Probe(ndim=2, si_units='um', name=probe.name, serial_number=probe.serial_number)
print(probe2.annotations)
{'name': 'probe_name'}
{'name': 'probe_name', 'serial_number': ''}
```
That is, an artificial empty annotation is created because of the way that the getter and the setter works.
After this PR this is fixed and re-instantiating the probe works as expected:
```python
from probeinterface import Probe
probe = Probe(ndim=2, si_units='um', name="probe_name")
print(probe.annotations)
probe2 = Probe(ndim=2, si_units='um', name=probe.name, serial_number=probe.serial_number)
print(probe2.annotations)
{'name': …
```
> Fix probe special properties setter

- src/probeinterface/probe.py
@h-mayorquin after discussion with Sam we think that this is a better behavior:
- return `None` if the annotation key is not present
- if setting an special annotation to `None`, remove if it's present
> Better handling of special annotations when None

- pyproject.toml
- src/probeinterface/probe.py
- tests/test_probe.py
As in the title. The probe can be serialized / marshalled to zarr and loaded.
This should come after #249 and #248
> Add save to zarr

- examples/ex_11_automatic_wiring.py
Old link was broken. New link looks like the intended target.
> Fix broken link in ex_11_automatic_wiring.py

- src/probeinterface/probe.py
- tests/test_probe.py
This is simlilar to "rect" (above view) but instead uses circular. This is for the pedestal type of connectors with Utah Array:
And this is how it looks.
> Add circular auto-shape option

- src/probeinterface/plotting.py
- tests/test_plotting.py
In regards to trying to get more api regularity the object is called a probegroup we don't ever write it as a probe_group. So I would say that to be consistent the plottting function should be plot_probegroup.
> plot_probe_group -> plot_probegroup

- src/probeinterface/plotting.py
- src/probeinterface/utils.py
`get_auto_lims` computes the boundaries of the given probe. It relies exclusively on vanilla Python and `numpy`. The `plotting` namespace, where the function is defined, imports `matplotlib`, that might not always be available. Hence, `get_auto_lims` should be independent on `matplotlib` and my suggestion is to move it to `utils`.
> Move get_auto_lims function to utils

- src/probeinterface/io.py
- tests/data/openephys/OE_Neuropix-PXI-multiple-signalchains/settings.xml
- tests/test_io/test_openephys.py
This is a proposal for a fix for a bug in which a NPX is not loaded if the Neuropix-PXI plugin is not in the first SIGNALCHAIN of an OpenEphys recording.
I have added an example settings.xml file and a test case
> probe is not loaded from OpenEphys

- src/probeinterface/utils.py
As anticipated in #281, I added a few lines of documentation to the `get_auto_lims` function in the `utils` namespace.
> Add docs to get_auto_lims

- pyproject.toml
- src/probeinterface/io.py
There has been a runtime dependency on `packaging` since ef8e7fd, but it's not listed in `pyproject.toml`. This caused an error when I tried to build a conda package for probeinterface.
`packaging.version.Version` was also imported but not used in `io.py`.
> Add "packaging" dependency to pyproject.toml

- resources/probe.json.schema
Dimensions can be float (triggered a validation error [here](https://github.com/SpikeInterface/probeinterface_library/actions/runs/10733469846/job/29766887227))
> Update schema to floats for radius, width, height, and planar_contour

- pyproject.toml
- resources/probe.json.schema
- src/probeinterface/probe.py
- src/probeinterface/testing.py
- tests/test_io/test_3brain.py
- tests/test_io/test_imro.py
- tests/test_io/test_maxwell.py
- tests/test_io/test_openephys.py
- tests/test_io/test_spikegadgets.py
- tests/test_io/test_spikeglx.py
I added some json schema validation to the tests and found a few minor discrepancies in the json schema
> add json validation to tests

- src/probeinterface/neuropixels_tools.py
@samuelgarcia 
While a was adding the new NXT probe (2020) I realize that we can get rid of the `oe_x_shift`. For both OE and SGLX we an assume that the left most electrode is at 0x, so we can just zero the x coordinate automatically. I tested with all probes and the OE and SGLX geometry is the same :)
Also found a bug in the OE contour, which we introduced when we fixed the "default".
Can you check this one?
> Remove `oe_x_shift`, add `NP2020`, and fix OE contour

- src/probeinterface/neuropixels_tools.py
- tests/data/openephys/OE_OneBox-NP-Ultra/settings.xml
- tests/test_io/test_openephys.py
> Support OneBox processor for Neuropixels-Open Ephys

- src/probeinterface/plotting.py
Retains previous default behaviour, but adds the option not to plot the collections on an axis, but just to return them. This is useful for incorporating the probe layout into other plots (such as SpikeInterface widgets).
> Allow plot_probe not to plot on axes, but just return polycollections

- src/probeinterface/neuropixels_tools.py
> Update #305 - Refactor Open Ephys

- doc/releases/0.2.27.rst
- pyproject.toml
Minor release with some Open Ephys and NP Quad-Base fixes
> Prepare release 0.2.27

- .github/workflows/full_tests.yml
It is a good practice to test as most users would consume the package: in its non-editable version.
> Tests on non-editable package

- resources/generate_neuropixels_library.py
- src/probeinterface/library.py
- src/probeinterface/neuropixels_tools.py
- src/probeinterface/probe.py
- tests/test_io/test_openephys.py
- tests/test_io/test_spikeglx.py
Better handling of model_name in neuropixels probe to generate the neuropixels library.
Now for instance:
`model_name = "NP1010"`
end 
`name = "Neuropixels 1.0 NHP short staggered probe with cap"`
This is more consistent <with the probeinterface_library.
Also change IMEC to imec.
Also handle float for positions
> Better handling of model_name in neuropixels probe to generate the neuropixels library

- src/probeinterface/neuropixels_tools.py
@samuelgarcia I'll make another PR for the release
> Add num_adcs, num_channels_per_adc, num_readout_channels, adc_bit_depth annotations to NP probes
